logging:
  level:
    io:
      spring:
        cloud:
          samples: INFO

fortune:
  fallbackFortune: Your future is unclear...

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 2
